name: Manual .NET build

on:
  workflow_dispatch

jobs:
  print-runtime-context:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸª Start build process
        run: echo "Build process has started..."

      - &echo-template
        name: Echo template
        run: echo "This is a reusable step"
        shell: bash

      - name: ğŸ“‹ Show runtime context
        run: |
          echo "ğŸŒ Runner OS: ${{ runner.os }}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸŒŠ Workflow: ${{ github.workflow}}"
          echo "â¡ï¸ Triggered by: ${{ github.event_name }}"
          echo "ğŸ­ Actor: ${{ github.actor }}"
          echo "ğŸ”¢ Run number: ${{ github.run_number }}"
          echo "ğŸªµ Branch: ${{ github.ref }}"

      - *echo-template

  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: install .NET 9
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.0.x'

      - name: Build project
        working-directory: CleanCodeDevops\CleanCodeDevops.app
        run: dotnet build

      - name: Run code
        working-directory: CleanCodeDevops\CleanCodeDevops.app
        run: dotnet run
