name: Manual .NET build

on:
  workflow_dispatch

jobs:
  print-runtime-context:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸª Start build process
        run: echo "Build process has started..."

      - name: ğŸ“‹ Show runtime context
        run: |
          echo "ğŸŒ Runner OS: ${{ runner.os }}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸŒŠ Workflow: ${{ github.workflow}}"
          echo "â¡ï¸ Triggered by: ${{ github.event_name }}"
          echo "ğŸ­ Actor: ${{ github.actor }}"
          echo "ğŸ”¢ Run number: ${{ github.runt_number }}"
          echo "ğŸªµ Branch: ${{ github.ref }}"
